<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionsTableSeeder extends Seeder
{
    public $moduleDef = [
        "1" => ['module' => 'Users'],
        "2" => ['module' => 'Requestable/Transfer Devices'],
        "3" => ['module' => 'Devices'],
        "4" => ['module' => 'Network Inventory'],
        "6" => ['module' => 'Accessories'],
        "7" => ['module' => 'Consumables'],
        "8" => ['module' => 'Licenses'],
        "9" => ['module' => 'Components'],
        "10" => ['module' => 'Status Board'],
        "11" => ['module' => 'Ticket'],
        "12" => ['module' => 'Ticket Basic Settings'],
        "14" => ['module' => 'Ticket Schedular'],
        "15" => ['module' => 'Ticket Trigger'],
        "16" => ['module' => 'Ticket Incident'],
        "19" => ['module' => 'Change'],
        "20" => ['module' => 'Task'],
        "21" => ['module' => 'Knowledge Document'],
        "22" => ['module' => 'Reports'],
        "23" => ['module' => 'Config'],
        "24" => ['module' => 'Problem Management'],
        "25" => ['module' => 'Schedule Maintenance'],
        "26" => ['module' => 'Project Management'],
        "27" => ['module' => 'Kanban Board'],
        "28" => ['module' => 'Patch Management'],
        "29" => ['module' => 'Live Monitor'],
        "30" => ['module' => 'Mailroom Management'],
        "31" => ['module' => 'Company'],
        "32" => ['module' => 'Email Logs'],
        "33" => ['module' => 'ITM Connect'],
        "34" => ['module' => 'Gate Pass'],
        "35" => ['module' => 'Software Tracking'],
    ];

    public function run()
    {

        $permissions = [
            'UserRead',
            'UserAdd',
            'UserEdit',
            'UserView',
            'UserDelete',
            'UserImport',
            'UserBulkUpdate',
            'UserMerge',
            'UserSendCredential',
            'UserDownload',
            'UserDevices',
            'UserDeviceCheckout',
            'UserLicences',
            'UserLicenceCheckin',
            'UserAccessories',
            'UserAccessoriesCheckin',
            'UserConsumables',
            'UserConsumablesRevoke',
            'UserComponents',
            'UserComponentsCheckout',
            'UserDocumentsUpload',
            'UserLog',
            'UserHistory',
            'UserPermission',
            'RequestableDevicesRead',
            'RequestableDevicesRequestSend',
            'AccessoriesRead',
            'AccessoriesAdd',
            'AccessoriesEdit',
            'AccessoriesView',
            'AccessoriesDelete',
            'AccessoriesDownload',
            'AccessoriesCheckout',
            'AccessoriesBulkCheckout',
            'AccessoriesCheckin',
            'AccessoriesDocumentsUpload',
            'DeviceRead',
            'DeviceAdd',
            'DeviceEdit',
            'DeviceView',
            'DeviceDelete',
            'DeviceDownload',
            'DeviceImport',
            'DeviceCheckoutCheckin',
            'DeviceResale',
            'DevicePrintLabel',
            'DeviceBulkUpdate',
            'DeviceBulkCheckout',
            'DeviceBulkCheckin',
            'DeviceSendReminder',
            'DeviceBulkSendReminder',
            'DeviceRestore',
            'DeviceRdpStatusUpdate',
            'DeviceBulkDelete',
            'DeviceDocumentsUpload',
            'NIRead',
            'NIView',
            'NIDownload',
            'NILicenseRead',
            'NILicenseDownload',
            'NIChangeDetailsRead',
            'NIDetectedHostRead',
            'NIDetectedHostEdit',
            'ConsumableRead',
            'ConsumableAdd',
            'ConsumableEdit',
            'ConsumableView',
            'ConsumableDelete',
            'ConsumableDownload',
            'ConsumableCheckout',
            'ConsumableBulkCheckout',
            'ConsumableCheckin',
            'ConsumableDocumentsUpload',
            'LicenseRead',
            'LicenseAdd',
            'LicenseEdit',
            'LicenseView',
            'LicenseDelete',
            'LicenseDownload',
            'LicenseCheckout',
            'LicenseBulkCheckout',
            'LicenseCheckin',
            'LicenseDocumentsUpload',
            'ComponentRead',
            'ComponentAdd',
            'ComponentEdit',
            'ComponentView',
            'ComponentDelete',
            'ComponentDownload',
            'ComponentCheckout',
            'ComponentBulkCheckout',
            'ComponentCheckin',
            'ComponentDocumentsUpload',
            'StatusBoardDashboard',
            'StatusBoardItemRead',
            'StatusBoardItemAdd',
            'StatusBoardItemEdit',
            'StatusBoardItemDelete',
            'StatusBoardGroupRead',
            'StatusBoardGroupAdd',
            'StatusBoardGroupEdit',
            'StatusBoardGroupDelete',
            'StatusBoardIncidentRead',
            'StatusBoardIncidentAdd',
            'StatusBoardIncidentEdit',
            'StatusBoardIncidentUpdateStatus',
            'StatusBoardIncidentHistory',
            'ChangeRequestDashboard',
            'ChangeRequestRead',
            'ChangeRequestAdd',
            'ChangeRequestEdit',
            'ChangeRequestView',
            'ChangeRequestDelete',
            'ChangeRequestDownload',
            'CABRead',
            'CABAdd',
            'CABEdit',
            'CABDelete',
            'CABMemberAdd',
            'CABMemberDelete',
            'AllTicket',
            'TicketDownload',
            'TicketConfiguration',
            'ProblemCategoriesRead',
            'ProblemCategoriesAdd',
            'ProblemCategoriesEdit',
            'ProblemCategoriesDelete',
            'ProblemCategoriesDownload',
            'ProblemCategoriesImport',
            'ProblemCategoriesEsclationAdd',
            'ProblemCategoriesEsclationEdit',
            'ProblemCategoriesEsclationDelete',
            'SchedularRead',
            'SchedularAdd',
            'SchedularEdit',
            'SchedularDelete',
            'SchedularDownload',
            'TicketTriggerRead',
            'TicketTriggerAdd',
            'TicketTriggerEdit',
            'TicketTriggerDelete',
            'TicketTriggerDownload',
            'TicketIncidentRead',
            'TicketIncidentAdd',
            'TicketIncidentEdit',
            'TicketIncidentView',
            'TicketIncidentDelete',
            'TicketIncidentDownload',
            'TaskRead',
            'TaskAdd',
            'TaskEdit',
            'TaskView',
            'TaskDelete',
            'TaskDownload',
            'NIDetectedHostDownload',
            'KnowledgeDocumentRead',
            'KnowledgeDocumentArticleRead',
            'KnowledgeDocumentArticleAdd',
            'KnowledgeDocumentArticleEdit',
            'KnowledgeDocumentArticleView',
            'KnowledgeDocumentArticleDelete',
            'KnowledgeDocumentCategoryRead',
            'KnowledgeDocumentCategoryAdd',
            'KnowledgeDocumentCategoryEdit',
            'KnowledgeDocumentCategoryDelete',
            'ActivityReport',
            'ActivityReportDownload',
            'NIDeviceWithMSOffice',
            'NIDeviceWithMSOfficeDownload',
            'NIDeviceWithMSOfficeUser',
            'NIDeviceWithMSOfficeUserDownload',
            'CategoryReport',
            'CategoryReportDownload',
            'DeviceAuditConfirmationReport',
            'DeviceAuditConfirmationReportDownload',
            'DeviceCheckoutAcceptReport',
            'DeviceCheckoutAcceptReportDownload',
            'CustomReport',
            'CustomReportAdd',
            'CustomReportEdit',
            'CustomReportView',
            'CustomReportDelete',
            'CustomReportDownload',
            'LocationReport',
            'LocationReportDownload',
            'PlaceReport',
            'PlaceReportDownload',
            'AccountTypeAssetReport',
            'AccountTypeAssetReportDownload',
            'StatusWiseDeviceReport',
            'StatusWiseDeviceReportDownload',
            'StatusWiseStockReport',
            'StatusWiseStockReportDownload',
            'LocationWisePurchaseReport',
            'LocationWisePurchaseReportDownload',
            'ContractDeviceReport',
            'ContractDeviceReportDownload',
            'StockDeviceReport',
            'StockDeviceReportDownload',
            'ScrapAccessoryReport',
            'ScrapAccessoryReportDownload',
            'DeletedAssetsReport',
            'DeletedAssetsReportDownload',
            'DeletedTicketsReport',
            'DeletedTicketsReportDownload',
            'DepartmentWiseReport',
            'DepartmentWiseReportDownload',
            'PlaceWiseReport',
            'PlaceWiseReportDownload',
            'DeviceReport',
            'DeviceReportDownload',
            'DeviceWarrantyReport',
            'DeviceWarrantyReportDownload',
            'DeviceAmcReport',
            'DeviceAmcReportDownload',
            'DeviceDepreciationReport',
            'DeviceDepreciationReportDownload',
            'DeviceMaintenanceReport',
            'DeviceMaintenanceReportDownload',
            'DeviceSoldReport',
            'DeviceSoldReportDownload',
            'ExpectedReturnReport',
            'ExpectedReturnReportDownload',
            'LicenseReport',
            'LicenseReportDownload',
            'LicenseSeatWiseReport',
            'LicenseSeatWiseReportDownload',
            'LicenseManufacturerWiseReport',
            'LicenseManufacturerWiseReportDownload',
            'LicenseUsageWiseReport',
            'LicenseUsageWiseReportDownload',
            'LicenseExpireReport',
            'LicenseExpireReportDownload',
            'TicketHandlerWiseReport',
            'TicketHandlerWiseReportDownload',
            'TicketDepartmentWiseReport',
            'TicketDepartmentWiseReportDownload',
            'TicketMergedReport',
            'TicketMergedReportDownload',
            'TicketEscalationReport',
            'TicketEscalationReportDownload',
            'TicketOverdueReport',
            'TicketOverdueReportDownload',
            'TicketReport',
            'TicketReportDownload',
            'TicketFeedbackReport',
            'TicketFeedbackReportDownload',
            'TicketReopenReport',
            'TicketReopenReportDownload',
            'TicketExceptionReport',
            'TicketExceptionReportDownload',
            'ThresholdWiseReport',
            'ThresholdWiseReportDownload',
            'AccessoriesReport',
            'AccessoriesReportDownload',
            'ConsumableReport',
            'ConsumableReportDownload',
            'ComponentReport',
            'ComponentReportDownload',
            'TicketAllocationGroupRead',
            'TicketAllocationGroupAdd',
            'TicketAllocationGroupEdit',
            'TicketAllocationGroupDelete',
            'TicketAllocationGroupUserRead',
            'TicketAllocationGroupUserAdd',
            'TicketAllocationGroupUserEdit',
            'TicketAllocationGroupUserDelete',
            'TechnicianLiveStatusRead',
            'TechnicianLiveStatusView',
            'TechnicianLiveStatusUpdate',
            'ConvertTicketToKnowledgeDocument',
            'TechnicianActivityLogReport',
            'NIDeviceNotDetectedReport',
            'NIBlacklistedSoftwareReport',
            'EditServiceTicket',
            'HolidaysRead',
            'HolidaysAdd',
            'HolidaysEdit',
            'HolidaysDelete',
            'HolidaysDownload',
            'ManufactureRead',
            'ManufactureAdd',
            'ManufactureEdit',
            'ManufactureDelete',
            'ManufactureDownload',
            'CategoryRead',
            'CategoryAdd',
            'CategoryEdit',
            'CategoryDelete',
            'CategoryDownload',
            'CategoryImport',
            'ModelRead',
            'ModelAdd',
            'ModelEdit',
            'ModelDelete',
            'ModelDownload',
            'ModelRestore',
            'ModelImport',
            'LocationRead',
            'LocationAdd',
            'LocationEdit',
            'LocationDelete',
            'LocationDownload',
            'LocationImport',
            'PlaceRead',
            'PlaceAdd',
            'PlaceEdit',
            'PlaceDelete',
            'PlaceDownload',
            'PlaceImport',
            'DepartmentRead',
            'DepartmentAdd',
            'DepartmentEdit',
            'DepartmentDelete',
            'DepartmentDownload',
            'DepartmentImport',
            'SupplierRead',
            'SupplierAdd',
            'SupplierEdit',
            'SupplierView',
            'SupplierDelete',
            'SupplierDownload',
            'SupplierImport',
            'PurchaseRead',
            'PurchaseAdd',
            'PurchaseEdit',
            'PurchaseView',
            'PurchaseDelete',
            'PurchaseDownload',
            'PurchaseImport',
            'PurchaseHistory',
            'ProjectRead',
            'ProjectAdd',
            'ProjectEdit',
            'ProjectDelete',
            'ProjectDownload',
            'ProjectImport',
            'StatusLabelRead',
            'StatusLabelAdd',
            'StatusLabelEdit',
            'StatusLabelDelete',
            'StatusLabelDownload',
            'StatusLabelImport',
            'CustomFieldRead',
            'CustomFieldAdd',
            'CustomFieldEdit',
            'CustomFieldDelete',
            'CustomFieldDownload',
            'DepreciationRead',
            'DepreciationAdd',
            'DepreciationEdit',
            'DepreciationDelete',
            'DepreciationDownload',
            'ContractAgreementRead',
            'ContractAgreementAdd',
            'ContractAgreementEdit',
            'ContractAgreementDelete',
            'ContractAgreementDownload',
            'ContractAgreementImport',
            'ThresholdRead',
            'ThresholdEdit',
            'SettingRead',
            'SettingEdit',
            'UserLocationRead',
            'UserLocationUpdate',
            'ProblemManagement',
            'MyProblemLists',
            'AllProblemLists',
            'AddProblemManagement',
            'EditProblemManagement',
            'DeleteProblemManagement',
            'ManageProblemManagement',
            'DownloadProblemManagement',
            'ManageTicketType',
            'TicketTypeRead',
            'TicketTypeAdd',
            'TicketTypeEdit',
            'TicketTypeView',
            'TicketTypeDelete',
            'TicketTypeDownload',
            'EmailReportTriggerRead',
            'EmailReportTriggerAdd',
            'EmailReportTriggerEdit',
            'EmailReportTriggerView',
            'EmailReportTriggerDelete',
            'EmailReportTriggerDownload',
            'UserEditRole',
            'ProblemCategoriesHistory',
            'ServiceRequestReport',
            'ServiceRequestReportDownload',
            'UserAssetReport',
            'DeviceMovement',
            'TicketAutoResolvedReport',
            'PlanView',
            'PlanAdd',
            'PlanEdit',
            'PlanDelete',
            'PlanDownload',
            'PlanRead',
            'PlanHistory',
            'PlanTaskAdd',
            'PlanTaskEdit',
            'PlanTaskDelete',
            'PlanTaskDownload',
            'PlanTaskRead',
            'PlanTaskHistory',
            'PlanTaskView',
            'PlanStatusView',
            'PlanStatusAdd',
            'PlanStatusEdit',
            'PlanStatusDelete',
            'PlanStatusRead',
            'AllocatePlanRead',
            'AllocatePlanAdd',
            'AllocatePlanEdit',
            'AllocatePlanDelete',
            'AllocatePlanDownload',
            'AllAssignPlanRead',
            'AllAssignPlanDownload',
            'AllAssignPlanCalendar',
            'MyAssignPlanRead',
            'MyAssignPlanDownload',
            'MyAssignPlanCalendar',
            'MyAssignPlanTaskView',
            'MyAssignPlanStatusEdit',
            'MyAssignPlanHistory',
            'MyAssignPlanTaskUpdate',
            'AllAllocatedDeviceRead',
            'AgentClientRead',
            'DeviceAudit',
            'AllAssignPlanTaskView',
            'KnowledgeDocumentCategoryDownload',
            'ChangeCategoryRead',
            'ChangeCategoryAdd',
            'ChangeCategoryEdit',
            'ChangeCategoryDelete',
            'ChangeCategoryDownload',
            'TransferRead',
            'TransferAdd',
            'TransferEdit',
            'TransferDownload',
            'CustomGraphRead',
            'InactiveUserReportRead',
            'InactiveUserReportBulkResolve',
            'InactiveUserReportDownload',
            'DeviceConfiguration',
            'ComplianceDashboardRead',
            'LiveMonitorAdd',
            'LiveMonitorRead',
            'LiveMonitorDelete',
            'LiveMonitorReminderAdd',
            'LiveMonitorReminderRead',
            'LiveMonitorReminderDelete',
            'MyProjectRead',
            'ProjectStatusRead',
            'ProjectClientRead',
            'ProjectStatusAdd',
            'ProjectStatusDelete',
            'ProjectView',
            'ProjectUsersAdd',
            'ProjectMilestoneRead',
            'ProjectMilestoneAdd',
            'ProjectMilestoneEdit',
            'ProjectMilestoneDelete',
            'ProjectUsersRead',
            'ProjectMilestoneView',
            'ProjectDocumentView',
            'ProjectDocumentAdd',
            'ProjectDocumentDelete',
            'ProjectDocumentDownload',
            'ProjectUsersHistoryView',
            'ProjectHistoryView',
            'ProjectHistory',
            'ProjectUsersHistory',
            'ProjectInfo',
            'ProjectUsersUpdate',
            'ProjectStatusEdit',
            'RdpAccess',
            'ClientRead',
            'ClientAdd',
            'ClientEdit',
            'ClientDelete',
            'ClientView',
            'ViewClientDocs',
            'AddClientDocs',
            'DeleteClientDocs',
            'DownloadClientDocs',
            'AddClientMember',
            'EditClientMember',
            'DeleteClientMember',
            'ClientHistoryView',
            'ImportClients',
            'AnnouncementRead',
            'AnnouncementAdd',
            'AnnouncementEdit',
            'AnnouncementDelete',
            'AnnouncementDownload',
            'AnnouncementMemberRead',
            'AnnouncementMemberAdd',
            'AnnouncementMemberEdit',
            'AnnouncementMemberDelete',
            'UserBasePermission',
            'UsbAdminAccessReport',
            'ServiceRequestBulkApproval',
            'TicketLocationWiseReport',
            'DelegateRequest',
            'DynamicFormRead',
            'DynamicFormAdd',
            'DynamicFormEdit',
            'DynamicFormView',
            'DynamicFormDelete',
            'DynamicFormDownload',
            'LiveMonitorWebsite',
            'LiveMonitorWebsiteAdd',
            'LiveMonitorWebsiteEdit',
            'LiveMonitorWebsiteView',
            'LiveMonitorWebsiteDelete',
            'LiveMonitorWebsiteDownload',
            'ChangeRequestListReport',
            'ChangeRequestDownloadReport',
            'LiveMonitorWebsiteAlertAdd',
            'LiveMonitorWebsiteAlertEdit',
            'LiveMonitorWebsiteAlertDelete',
            'LiveMonitorWebsiteAlertView',
            'LiveMonitorWebsiteIncidentView',
            'LiveMonitorWebsiteIncidentResolve',
            'MaintenanceDashboardRead',
            'DeviceTypeRead',
            'DeviceTypeAdd',
            'DeviceTypeEdit',
            'DeviceTypeDelete',
            'DeviceTypeDownload',
            'LiveMonitorWebsiteMemberRead',
            'LiveMonitorWebsiteMemberAdd',
            'LiveMonitorWebsiteMemberEdit',
            'LiveMonitorWebsiteMemberDelete',
            'LiveMonitorWebsiteAlertDownload',
            'LiveMonitorWebsiteIncidentDownload',
            'LiveMonitorDashboard',
            'CustomTaxRead',
            'CustomTaxAdd',
            'CustomTaxEdit',
            'CustomTaxDelete',
            'CustomTaxDownload',
            'ProcurementReportRead',
            'ProcurementReportDownload',
            'ProcurementItemReportRead',
            'ProcurementItemReportDownload',
            'AllocationTypeRead',
            'AllocationTypeAdd',
            'AllocationTypeEdit',
            'AllocationTypeDelete',
            'AllocationTypeDownload',
            'Kanban',
            'KanbanAllBoards',
            'KanbanMyBoards',
            'KanbanBoardAdd',
            'KanbanBoardEdit',
            'KanbanBoardDelete',
            'KanbanBoardMembers',
            'KanbanBoardAddMembers',
            'KanbanBoardEditMembers',
            'KanbanBoardDeleteMembers',
            'PatchManagerRead',
            'PatchManagerDownload',
            'PatchManagerRequest',
            'PatchManagerRequestRead',
            'SoftwareDeploymentRead',
            'SoftwareDeploymentAdd',
            'SoftwareDeploymentEdit',
            'SoftwareDeploymentDelete',
            'SoftwareDeploymentRequest',
            'SoftwareDeploymentRequestRead',
            'SoftwareDeploymentRequestDelete',
            'SoftwareDeploymentGroupRead',
            'SoftwareDeploymentAddGroup',
            'SoftwareDeploymentEditGroup',
            'SoftwareDeploymentDeleteGroup',
            'MailroomDashboardView',
            'MailroomParcelsView',
            'MailroomParcelsCreate',
            'MailroomParcelsEdit',
            'MailroomParcelsDelete',
            'MailroomParcelsImport',
            'MailroomParcelsUpdateStatus',
            'MailroomParcelsViewInfo',
            'MailroomParcelsViewHistory',
            'MailroomParcelsViewDeliveryInfo',
            'MailroomSitesView',
            'MailroomSitesCreate',
            'MailroomSitesEdit',
            'MailroomSitesDelete',
            'MailroomStatusesView',
            'MailroomStatusesCreate',
            'MailroomStatusesEdit',
            'MailroomStatusesDelete',
            'MailroomUsersView',
            'MailroomUsersCreate',
            'MailroomUsersEdit',
            'MailroomUsersDelete',
            'MailroomParcelsPrintLabel',
            'MailroomParcelsBulkAction',
            'MailroomParcelsHistory',
            'MailroomParcelsBulkPrintLabel',
            'MailroomParcelsPrintInvoice',
            'PatchManagerDashboard',
            'MailroomParcelsReportView',
            'MailroomParcelsReportDownload',
            'MailroomParcelsStatusReportView',
            'MailroomParcelsStatusReportDownload',
            'MailroomParcelsReport',
            'TaskDashboard',
            'TicketTaskReport',
            'TaskHistory',
            'PrivilegeCategoryRead',
            'PrivilegeCategoryDownload',
            'CompanyView',
            'CompanyAdd',
            'CompanyRead',
            'CompanyEdit',
            'CompanyDelete',
            'CompanyDownload',
            'UserDocumentsDelete',
            'DeviceDocumentsDelete',
            'AccessoriesDocumentsDelete',
            'ConsumableDocumentsDelete',
            'LicenseDocumentsDelete',
            'ComponentDocumentsDelete',
            'IndividualMaterialRead',
            'IndividualMaterialDownload',
            'PatchAdd',
            'PatchEdit',
            'PatchRead',
            'PatchDelete',
            'PatchManagerRequestDelete',
            'ThresholdLevelRead',
            'ThresholdLevelDownload',
            'MailroomParcelsVendorReportDownload',
            'MailroomParcelsVendorReportView',
            'Du/BuHeadView',
            'DailyDistributionRead',
            'DailyDistributionDownload',
            'KanbanCutomBoardCardAdd',
            'KanbanCutomBoardCardEdit',
            'KanbanCutomBoardCardDelete',
            'KanbanCutomBoardCardClone',
            'KanbanBoardImport',
            'KanbanBoardExport',
            'KanbanBoardGroupBy',
            'MonthWiseConsumableRead',
            'MonthWiseConsumableDownload',
            'DeviceRFIDReport',
            'NiErrorLogReportDownload',
            'NiErrorLogReport',
            'KanbanViewArchivedCards',
            'ConsumableRestore',
            'AccessoriesRestore',
            'LicenseRestore',
            'ProcureAccountTypeRead',
            'ProcureAccountTypeEdit',
            'ProcureAccountTypeAdd',
            'ProcureAccountTypeDelete',
            'ConsumableScrap',
            'ConsumableRevertScrap',
            'MyTicketRead',
            'KanbanMemberViewHistory',
            'ComponentRestore',
            'KanbanBoardViewHistory',
            'TicketAddToProblemManagement',
            'TicketAddToIncident',
            'EmailLogRead',
            'EmailLogDownload',
            'ITMConnect',
            'ITMCalls',
            'ITMConnectCall',
            'ITMConnectConvertToTicket',
            'ITMConnectDownload',
            'ITMConnectView',
            'DeviceExpenseRead',
            'DeviceExpenseEdit',
            'DeviceExpenseDelete',
            'DeviceExpenseDownload',
            'DeviceAccounting',
            'PurchaseDocumentView',
            'PurchaseDocumentDelete',
            'PurchaseDocumentDownload',
            'PurchaseDocumentAdd',
            'DeviceExpenseAdd',
            'GatePassRead',
            'GatePassAdd',
            'GatePassEdit',
            'GatePassDelete',
            'GatePassExport',
            'PatchConfiguration',
            'PatchManagerRequestApproval',
            'PatchConfigurationRuleAdd',
            'PatchConfigurationRuleDelete',
            'PatchConfigurationRuleChangeStatus',
            'PatchConfigurationRuleRead',
            'PatchManagerDeploymentRequestRead',
            'PatchManagerDeploymentRequestApproval',
            'AccessoriesScrap',
            'AccessoriesRevertScrap',
            'KanbanConfiguration',
            'AzureSyncUsers',
            'SoftwareUsesTimeReport',
            'SoftwareUsesTimeReportDownload',
            'ComponentPrintLabel',
            'TechnicianManageOthers',
            'SoftwareUsageRead',
            'SoftwareUsageDownload',
            'UserPrintLabel',
            'TicketAllocationGroupMemberImport',
            'TicketAllocationGroupImport',
        ];

        foreach ($permissions as $permission) {

            $moduleId = $this->detectModuleId($permission);

            Permission::updateOrCreate(
                ['name' => $permission],
                [
                    'guard_name' => 'web',
                    'module_id' => $moduleId
                ]
            );
        }
    }

    /**
     * Detect module_id from permission name
     */
    private function detectModuleId($permission)
    {
        $map = [
            'User' => 1,
            'RequestableDevices' => 2,
            'Device' => 3,
            'NI' => 4,
            'Accessories' => 6,
            'Consumable' => 7,
            'License' => 8,
            'Component' => 9,
            'StatusBoard' => 10,
            'Ticket' => 11,
            'Task' => 20,
            'KnowledgeDocument' => 21,
            'Report' => 22,
            'Manufacture' => 23,
            'Problem' => 24,
            'Project' => 26,
            'Kanban' => 27,
            'Patch' => 28,
            'LiveMonitor' => 29,
            'Mailroom' => 30,
            'Company' => 31,
            'EmailLog' => 32,
            'ITM' => 33,
            'GatePass' => 34,
            'Software' => 35
        ];

        foreach ($map as $key => $moduleId) {
            if (str_starts_with($permission, $key)) {
                return $moduleId;
            }
        }

        return null;
    }
}
